package io.omnitrade.enumerator.k

enum class Period(val time: Int) {
  ONE(1),
  FIVE(5),
  FIFTEEN(15),
  THIRTY(30),
  SIXTY(60),
  ONE_HUNDRED_TWENTY(120),
  TWO_HUNDRED_FORTY(240),
  THREE_HUNDRED_SIXTY(360),
  SEVEN_HUNDRED_TWENTY(720),
  ONE_THOUSAND_FOUR_HUNDRED_FORTY(1440),
  FOUR_THOUSAND_THREE_HUNDRED_TWENTY(4320),
  TEN_THOUSAND_EIGHTY(10080)
}
